### ISSUE TITLE
Creation of the systemd file within container_lifecycle

### ISSUE THREAD

**Issue by rlopez133** [hybrid-cloud-patterns/ansible-edge-gitops#24]
You shouldn't need to create the systemd unit file found here: https://github.com/hybrid-cloud-patterns/ansible-edge-gitops/blob/main/ansible/roles/container_lifecycle/tasks/main.yml#L19-L23 

You should be able to do something similar to this (mind you pseudo code didn't attempt):

```
- name: Re-create {{ container_image }} container with systemd service file generated in /tmp/
  containers.podman.podman_container:
    name: "{{ container_image }}"
    image: "{{ container_image }}:{{ container_tag }}"
    state: present
    recreate: yes
    generate_systemd:
      path: /tmp/
      restart_policy: on-failure
      new: yes
      container_prefix: afiot
```

Recreate will always recreate a matching container. I figure if a container was created and didn't have the systemd you wanted, you should recreate. Also if non-exists, it will start one. 

more info: https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html
